
title = "I'm Tinalang"
author = "Tianlang"
#copyright = "2020-2022"
description = "Call me "
profilePicture = "images/主页头像.jpeg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-brands fa-bilibili"
title = "bilibili"
url = "https://space.bilibili.com/1910032766?spm_id_from=333.1007.0.0"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/tianlangz"

[[socialIcons]]
icon = "fab fa-brands fa-gitlab"
title = "Gitlab"
url = "https://gitlab.com/tianlangz"

[[socialIcons]]
icon = "fab fa-brands fa-steam"
title = "steam"
url = "https://steamcommunity.com/profiles/76561198428670521/"

[[socialIcons]]
icon = "fab fa-d-and-d"
title = "CSDN"
url = "https://blog.csdn.net/TianLangZ"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "https://mail.qq.com/cgi-bin/frame_html?sid=RryfvW32kcaHB189&r=37c431417c0209ba54bfdf2d9ce32a35"

# [[socialIcons]]
# icon = "fad fa-monkey"
# title = "CSDN"
# url = "https://blog.csdn.net/TianLangZ"

